# Ice Cream Sales Revenue Dataset 2023

In [71]:
# step 1 : import library
import pandas as pd

In [72]:
# step 2 : import data
ice_cream = pd.read_csv('Ice Cream.csv')
ice_cream.head()

Temperature  Revenue
0         24.6      535
1         26.1      626
2         27.8      661
3         20.6      488
4         11.6      317

In [73]:
ice_cream.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    int64  
dtypes: float64(1), int64(1)
memory usage: 7.9 KB


In [74]:
ice_cream.describe()

Temperature      Revenue
count   500.000000   500.000000
mean     22.281600   522.058000
std       8.097597   175.410399
min       0.000000    10.000000
25%      17.175000   406.000000
50%      22.400000   530.000000
75%      27.800000   643.000000
max      45.000000  1000.000000

In [75]:
# step 3 : Define target y and  X features 
X = ice_cream['Temperature'].values.reshape(-1, 1)
y = ice_cream['Revenue'].values.reshape(-1, 1)


In [76]:
# step 4 : train test split the data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=2529,test_size=0.7)

In [77]:
# step 5 : select the model
from sklearn.linear_model import LinearRegression,LogisticRegression
# model = LinearRegression()
model = LogisticRegression()

In [78]:
# step 6 : train the model
model.fit (X_train,y_train)

c:\Users\Vikas\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Vikas\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [79]:
model.intercept_

array([ 37.43604743,  30.36406386,  25.84845846,  24.76066638,
        21.7649908 ,  22.98560588,  19.31012141,  22.7763428 ,
        18.39126876,  20.05984862,  36.21948327,  19.87164251,
        17.67629835,  14.89828709,  11.90437868,  17.50028502,
        13.37708189,  15.760787  ,  17.67629835,  14.72677277,
        18.75567085,  15.58759814,  12.88254828,  13.87782997,
        14.0462047 ,  13.37708189,  15.760787  ,  13.21161212,
        16.80203894,   8.9997124 ,  23.46229367,  10.28573693,
         7.5577692 ,   9.32051047,   9.64168907,   9.48104401,
         7.39748196,   3.21679719,   7.07683576,   8.03848351,
         4.50522702,   6.75605214,   1.44680777,   9.40476065,
         2.08998725,   3.21679719,   0.80437352,   4.66623877,
         6.11388487,   0.96490349,   8.83443395,   2.2508784 ,
         1.44680777,   4.1831521 ,   3.05575933,   6.2086484 ,
         0.32312944,  -0.31764619,   3.80880584,  -0.15755268,
        -0.63762171,   1.7683148 ,   1.60753924,   0.48

In [80]:
model.coef_

array([[-3.7848057 ],
       [-2.44270167],
       [-1.81874591],
       [-1.68117625],
       [-1.37155587],
       [-1.49320608],
       [-1.11629217],
       [-1.47229957],
       [-1.04493821],
       [-1.18229775],
       [-3.15648873],
       [-1.16465794],
       [-0.97802294],
       [-0.72845315],
       [-0.50856319],
       [-0.95630247],
       [-0.6187524 ],
       [-0.80262284],
       [-0.97802294],
       [-0.71611789],
       [-1.07302959],
       [-0.78769755],
       [-0.58293251],
       [-0.65499815],
       [-0.66767242],
       [-0.6187524 ],
       [-0.80262284],
       [-0.60688562],
       [-0.88994057],
       [-0.32936734],
       [-1.42588703],
       [-0.41603238],
       [-0.24875562],
       [-0.35041819],
       [-0.37264173],
       [-0.36138197],
       [-0.24029609],
       [-0.01754662],
       [-0.22266482],
       [-0.27346938],
       [-0.08257252],
       [-0.2044248 ],
       [ 0.06825973],
       [-0.30228543],
       [ 0.03748743],
       [-0

In [81]:
# step 7 : predict the model
y_pred = model.predict(X_test)

In [82]:
y_pred

array([644, 426, 243, 336, 426, 336, 426, 644, 644, 644, 595, 595, 426,
       336, 243, 494, 595, 595, 521, 857, 336, 451, 451, 857, 595, 336,
       644, 258, 521, 478, 644, 857, 595, 595, 426, 426, 426, 644, 857,
       595, 857, 644, 494, 426, 595, 857, 451, 857, 644, 522, 426, 494,
       494, 595, 644, 478, 644, 644, 426, 644, 521, 258, 426, 243, 426,
       644, 451, 426, 644, 857, 595, 426, 644, 426, 336, 478, 595, 243,
       595, 644, 644, 595, 478, 857, 644, 857, 595, 857, 426, 451, 595,
       644, 595, 243, 595, 595, 595, 494, 478, 595, 521, 336, 644, 494,
        10, 426, 595, 478, 595, 595, 644, 522, 426, 644, 451, 258, 478,
       426, 478, 595, 538, 336, 644, 644, 426, 644, 644, 538, 258, 595,
       857, 595, 644, 644, 478, 595, 595, 595, 478, 451, 595, 521, 595,
       494, 451, 644, 426, 478, 426, 336, 644, 538, 857, 258, 644, 478,
       426, 258, 595, 857, 644, 336, 478, 478, 478, 644, 243, 521, 426,
       336, 522, 426, 478, 521, 426, 595, 595, 595, 336, 595, 85

In [83]:
# Model accuracy
from sklearn.metrics import accuracy_score,mean_absolute_error,mean_absolute_percentage_error,mean_squared_error
accuracy_score(y_test,y_pred)

0.017142857142857144

In [84]:
mean_absolute_percentage_error(y_test,y_pred)

0.10956537743413995

In [86]:
model.predict([[20]])

array([494], dtype=int64)